# This is a basic workflow to help you get started with Actions

name: deploy

on:
  push:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: xmflsct/action-publish-gatsby@v1
        with:
          token: ${{ secrets.TOKEN }}
